witmy: &witmy
  docker:
    - image: circleci/node:14.17.3

version: 2
jobs:
  test:
    <<: *witmy
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    <<: *witmy
    steps:
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    <<: *witmy
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy Main to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  test-branch:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
      - build:
          requires:
            - test
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
